export const ADD_SONG_TO_PLAYLIST = 'ADD_SONG_TO_PLAYLIST';
export const DELETE_MUSIC_FROM_PLAYLIST = 'DELETE_MUSIC_FROM_PLAYLIST';
export const CREATE_PLAYLIST = 'CREATE_PLAYLIST';
export const DELETE_PLAYLIST = 'DELETE_PLAYLIST';